### ISSUE TITLE
zstd is implemented incorrectly

### ISSUE THREAD

**Issue by Finomnis** [Speedy37/speedupdate-rs#8]
Your zstd compression algorithm is only that fast because it doesn't actually do anything.
You write directly into its output buffer and then read from it again, effectively bypassing the entire compression step.

Just wanted to let you know, as it came up in a stackoverflow post:

https://stackoverflow.com/questions/74739857/switch-from-brotly-sys-to-dropbox-brotli/74740490#74740490

**Comment by Speedy37** [comment]
I'm quite sure you are wrong, in stackoverflow you are writing to `Coder::get_input_writer()`, i'm not, `Coder` is there so I can access directly the "inner" Writer so I can check both the input and output checksum in a single pass.
I'm not bypassing the writer.

**Comment by Finomnis** [comment]
I guess I must have misunderstood your code then :)
